version: '3.8'

services:
  # PostgreSQL database service
  database:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: BoothDB
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: booth-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - database
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: ./Backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: booth-web
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - backend
    volumes:
      - ./frontend/app:/app/app

volumes:
  database_data:
